name: merge draft
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: |
          declare -A branches
          branches["issue_8"]="source/tutorial"
          branches["issue_14"]="source/tutorial"
          branches["tutorial3_alphalens_lesson1_to_5"]="source/tutorial"
          for branch in ${branches[@]} 
          do 
            echo $branch
          done
          echo ${SOURCE_REPOSITORY}
          git clone ${SOURCE_REPOSITORY}
          cd ${REPOSITORY_DIR}
          for branch in "${!branches[@]}"
          do
            # echo "${branch}:${branches[${branch}]}"
            git fetch origin ${branch}
          done
          for branch in "${!branches[@]}"
          do
            git checkout origin ${branch}
          done
          git checkout origin master
          cd ..
        env:
          SOURCE_REPOSITORY: https://github.com/tokyoquantopian/quantopian-doc-ja.git
          REPOSITORY_DIR: quantopian-doc-ja
