name: merge draft
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: |
          for x in $NAMES; do
            echo $x
          done
        env:
          NAMES: AAA BBB
