name: merge draft
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: |
          declare -A exam
          exam["suzuki"]=80
          exam["tanaka"]=95
          exam["yamamoto"]=90
          for e in ${exam[@]} 
          do 
            echo $e
          done
          echo ${SOURCE_REPOSITORY}
          git clone ${SOURCE_REPOSITORY}
          cd ${REPOSITORY_DIR}
        env:
          SOURCE_REPOSITORY: https://github.com/tokyoquantopian/quantopian-doc-ja.git
          REPOSITORY_DIR: quantopian-doc-ja
